### ISSUE TITLE
how does one perform createEconomicEvent without error?

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#183]
I can't figure out what should be the input for `provider` and `receiver` that won't cause an error. 

```
mutation MyMutation {
  createEconomicEvent(event: {action: "finishes", provider: "uhCAkDU5IjRgXp-V0M0rByc9DquhlUtLSPkTkRY5ZnSlnAEbYHddC", receiver: "uhCAkDU5IjRgXp-V0M0rByc9DquhlUtLSPkTkRY5ZnSlnAEbYHddC"}) {
    economicResource {
      id
    }
  }
}
```

I have tried both with and without the dnahash prefix section of the AgentAddress

I get either
Deserialize("HoloHash error: BadPrefix(\"DnaHash\", [132, 32, 36])")
or
Deserialize("invalid type: string \"uhCAkDU5IjRgXp-V0M0rByc9DquhlUtLSPkTkRY5ZnSlnAEbYHddC\", expected tuple struct AgentAddress"

```
 ERROR wasm_trace: hc_zome_rea_economic_event::__create_economic_event_extern:zomes/rea_economic_event/zome/src/lib.rs:59 output_type = "core::result::Result<hc_zome_rea_economic_event_rpc::ResponseData, holochain_wasmer_common::result::WasmError>"; bytes = [130, 165, 101, 118, 101, 110, 116, 131, 166, 97, 99, 116, 105, 111, 110, 168, 102, 105, 110, 105, 115, 104, 101, 115, 168, 112, 114, 111, 118, 105, 100, 101, 114, 146, 196, 39, 132, 32, 36, 13, 78, 72, 141, 24, 23, 167, 229, 116, 51, 74, 193, 201, 207, 67, 170, 232, 101, 82, 210, 210, 62, 68, 228, 69, 142, 89, 157, 41, 103, 0, 70, 216, 29, 215, 66, 196, 39, 132, 45, 36, 235, 142, 179, 94, 68, 10, 54, 240, 180, 190, 17, 36, 67, 21, 190, 136, 104, 40, 32, 177, 184, 249, 11, 107, 117, 76, 131, 53, 220, 232, 9, 180, 100, 56, 197, 206, 168, 114, 101, 99, 101, 105, 118, 101, 114, 146, 196, 39, 132, 32, 36, 13, 78, 72, 141, 24, 23, 167, 229, 116, 51, 74, 193, 201, 207, 67, 170, 232, 101, 82, 210, 210, 62, 68, 228, 69, 142, 89, 157, 41, 103, 0, 70, 216, 29, 215, 66, 196, 39, 132, 45, 36, 235, 142, 179, 94, 68, 10, 54, 240, 180, 190, 17, 36, 67, 21, 190, 136, 104, 40, 32, 177, 184, 249, 11, 107, 117, 76, 131, 53, 220, 232, 9, 180, 100, 56, 197, 206, 184, 110, 101, 119, 95, 105, 110, 118, 101, 110, 116, 111, 114, 105, 101, 100, 95, 114, 101, 115, 111, 117, 114, 99, 101, 192]; Deserialize("HoloHash error: BadPrefix(\"DnaHash\", [132, 32, 36])")

Jan 03 15:31:27.868 ERROR wasm_trace: hc_zome_rea_economic_event::__create_economic_event_extern:zomes/rea_economic_event/zome/src/lib.rs:59 output_type = "core::result::Result<hc_zome_rea_economic_event_rpc::ResponseData, holochain_wasmer_common::result::WasmError>"; bytes = [130, 165, 101, 118, 101, 110, 116, 131, 166, 97, 99, 116, 105, 111, 110, 168, 102, 105, 110, 105, 115, 104, 101, 115, 168, 112, 114, 111, 118, 105, 100, 101, 114, 217, 53, 117, 104, 67, 65, 107, 68, 85, 53, 73, 106, 82, 103, 88, 112, 45, 86, 48, 77, 48, 114, 66, 121, 99, 57, 68, 113, 117, 104, 108, 85, 116, 76, 83, 80, 107, 84, 107, 82, 89, 53, 90, 110, 83, 108, 110, 65, 69, 98, 89, 72, 100, 100, 67, 168, 114, 101, 99, 101, 105, 118, 101, 114, 217, 53, 117, 104, 67, 65, 107, 68, 85, 53, 73, 106, 82, 103, 88, 112, 45, 86, 48, 77, 48, 114, 66, 121, 99, 57, 68, 113, 117, 104, 108, 85, 116, 76, 83, 80, 107, 84, 107, 82, 89, 53, 90, 110, 83, 108, 110, 65, 69, 98, 89, 72, 100, 100, 67, 184, 110, 101, 119, 95, 105, 110, 118, 101, 110, 116, 111, 114, 105, 101, 100, 95, 114, 101, 115, 111, 117, 114, 99, 101, 192]; Deserialize("invalid type: string \"uhCAkDU5IjRgXp-V0M0rByc9DquhlUtLSPkTkRY5ZnSlnAEbYHddC\", expected tuple struct AgentAddress")
```

I'm sure I'm just missing something basic about how to do this. 

I'd like to be able to know how, so that I can experiment a bit further with it.

**Comment by pospi** [comment]
Actually this is probably something weird that I'm doing with my double-length hashes which specify a `DnaHash` as context for every `DnaAddressable` and `AgentPubKey`. (The hope is, this allows the most flexibility in many:many DNA relationships where network spaces mimic intersecting organisational boundaries.)

Try this one:

```graphql
{
  myAgent {
    id
    name
  }
}
```

> (Though I am [mostly mocking it](https://github.com/holo-rea/holo-rea/blob/212fe57/modules/vf-graphql-holochain/queries/agent.ts#L31) in the GraphQL layer at the moment, it doesn't connect to any [Profiles](https://github.com/holochain-open-dev/profiles) or other fancy things but I would love any advice / help on integrating those.)

You can take the ID from there but only now that I've fixed 5f29bfb1 (sorry... I had one in my GraphiQL cache with a valid format and no idea how long it's been there for) and pass to the other queries. For completeness, a simple valid `EconomicEvent` can be created via something like the below; you shouldn't need to substitute `provider` & `receiver` unless you really want to since there are no cross-DNA referential integrity checks (yet).

```graphql
mutation(
  $event: EconomicEventCreateParams!,
  $resource: EconomicResourceCreateParams!,
) {
  createEconomicEvent(event: $event, newInventoriedResource: $resource) {
    economicEvent {
      id
      note
      hasPointInTime
    }
    economicResource {
      id
      classifiedAs
    }
  }
}
```

```json
{"event": {
  "resourceClassifiedAs": ["avocados", "haas avocados"],
  "hasPointInTime": "2019-11-19T04:29:45.000Z",
  "action": "raise",
  "provider": "uhCAkJCs_Z9CHqVCTBPtkCXyhQi3Z0L1oop8Lz0oZGZqSbSeCB_F8:uhC0kBXjbhKE1giZXpnbMZ9LfSConfoDQTzyCm2XM6jeKEkDaBM7s",
  "receiver": "uhCAkJCs_Z9CHqVCTBPtkCXyhQi3Z0L1oop8Lz0oZGZqSbSeCB_F8:uhC0kBXjbhKE1giZXpnbMZ9LfSConfoDQTzyCm2XM6jeKEkDaBM7s",
  "resourceQuantity": { "hasNumericalValue": 3 },
  "note": "I've got 3 avocadoes"
},
"resource": { "note": "my avocados" }}
```

**Comment by pospi** [comment]
Oh, another note on this- in lieu of #184 you will get errors doing the list-based queries; but you can check out the data structures with `npm run playground ws://localhost:XXXXX` from within the tests folder if you like.

**Comment by Connoropolous** [comment]
Ah, ok, yeah I was passing the Id i got back from the my agent query, but that wasn't yet working. What makes your bug fix work, when it didn't before? I see you swapped the order. 

Thanks!

**Comment by pospi** [comment]
Yeah, that's pretty much it. My first pass at a working many:many relationship structure between records in different DNAs is to concatenate the `DnaHash` for every `EntryHash` where a record is referenced via an identifier. 

As with all these things, the ordering of parameters has often been the most confusing part :sweat_smile: 

Thought this screenshot might be of interest, to give a little more detail as to the link structures these CRUD libraries create on the DHT-

![image](https://user-images.githubusercontent.com/437540/148712122-f7a8c6d0-7f4a-47f6-9d3c-78fde51ce979.png)

The top 3 entries are `hdk::Path` nodes building a sparsely populated unordered index for all records stored in a zome. In the near future, this will probably be replaced with https://github.com/holochain-open-dev/holochain-time-index so that the bundled indexing for querying records has more utility (ie. being able to easily query records by their creation time).

The left hand node is a `Process`; the right-hand nodes are 3 versions of another separate `Process`, each referencing the root (initiating) revision such that it can be inferred at runtime and used as a stable record ID [in combination with the host `DnaHash`](https://github.com/holo-rea/holo-rea/blob/732bbea/lib/hdk_records/src/record_helpers.rs#L154) in both this & remote DNAs.
