### ISSUE TITLE
ensure all integration tests passing or skipped

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#216]
It's looking like the "Planning" suite is the remaining one with indexing configuration related issues #252 , #254, and #255.

```
343 passed
13 failed
...........................................................................................................
...........................................................................................................
.........x.x.......x.....xx..................................................xxx.........x......x..
xx........................................x
```

- [x] #263
- [x] #257
- [x] #247
- [x] `test/economic-event` has 13/13 assertions passing
- [x] #253
- [x] #246
- [x] #248
- [x] #249
- [x] #254
- [x] #255
- [x] #252
- [x] #251
- [x] #256
- [x] #250

The below task is not the only sub-task, just one of many possible ones.
- [x] #242

**Comment by Connoropolous** [comment]
@pospi I am trying out this library tap-dot instead of `faucet` for the test out put since I am finding the faucet output very difficult to get a read on. 

https://github.com/scottcorgan/tap-dot

It is giving me a nice output like this: 
<img width="442" alt="Screen Shot 2022-04-11 at 7 56 47 PM" src="https://user-images.githubusercontent.com/1409121/162870323-0bb13335-462c-44f1-b479-83d76aa3c30a.png">

Before any other progress on the tests is made, how can we organize the tests, such that perhaps only the ones that are updated, and the ones that are passing, are running?

The problem right now is that there's no way for me to tell which ones are passing and which ones aren't. Is there some solution we can come up with for this?

**Comment by pospi** [comment]
> The problem right now is that there's no way for me to tell which ones are passing and which ones aren't. Is there some solution we can come up with for this?

I am still working through them one directory at a time, and just running the commands piecemeal for now. We could create a completion matrix for them if you think it's too cumbersome to proceed in that way?

**Comment by pospi** [comment]
Some notes on what typically needs updating in each test script:

- player initialisation logic changes need to use the new `buildConfig` and `buildPlayer` API format (doing these will actually get you into the test logic proper)
- you need to use the mocking methods from `init.js` to mock identifiers in order for the backend to accept them. There is `mockAddress()` for `EntryHash`-based IDs; `mockAgentId()` for `AgentPubKey`-based IDs (which will largely go away after #219); and `mockldentifier()` for string-based IDs (such as `UnitId`). The default for these methods is to generate identifiers as strings for passing to the GraphQL layer. Tests using the low-level `call` API should pass `true` as an argument to generate raw `Buffer` objects appropriate for passing directly to Holochain.
- identifier equality needs to be asserted with `deepEqual` rather than `equal` now, since `Buffer` objects behave differently to strings
- updates & deletes need to be made with the appropriate record `revisionId` now, as opposed to `id`
- handling of errors needs to be done with try/catch now, rather than looking for an `err` property in the response

**Comment by Connoropolous** [comment]
Thanks for documenting that, that may be very useful!

**Comment by pospi** [comment]
All seems to be well now, am seeing 442 passed tests and no failures.
