### ISSUE TITLE
Multi-DNA integration tests fail randomly due to timeouts

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#218]
This causes errors of the form 

    "    data: "ZomeError: Zome not found: Zome 'XXXX' not found"

See https://github.com/holochain/tryorama/issues/106

**Comment by pospi** [comment]
Temporary workaround added in bfde90bd

**Comment by Connoropolous** [comment]
since this isn't blocking at the moment, and we have longer term open questions about tryorama and related updates, we could just close this. The only other option (would be good with it also) would be to change the name of the issue to be 'un-hack the temporary tryorama hack' and point back to the commit and the related code, such that we're basically tracking that 'todo' in the code.
