### ISSUE TITLE
Pagination cursors

### ISSUE THREAD

**Issue by Connoropolous** [holo-rea/holo-rea#222]
Finish logic for determining cursors for output- though the data structures are present, currently only placeholders are returned.

**Comment by pospi** [comment]
What's missing here is an easy way of converting the `(DnaHash, EntryHash)` record ID tuples from `hdk_uuid_types` into a string. Currently the conversion just fails and falls through to a default, which is an empty string.

Very open to custom serialization logic for this, though we should *probably* use `HoloHashB64`, even though it may be removed in favour of some base64 encoding host function in future (doing it within the zome requires a B64 library to be compiled into the zome, and these are somewhat heavyweight).

The resulting solution should be wrapped up into library code in `hdk_relay_pagination` so that zomes don't have to duplicate it (see #221)
