### ISSUE TITLE
Debug statements not being output to console in integration tests

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#305]
Something in the most recent set of infrastructural updates has broken `debug!` output- it no longer shows in integration tests when running with my previous env vars or the ones defined in `test/package.json`.

May also be due to the most recent HDK update, but unsure.

Blocked on #221 until this is resolved.

**Comment by Connoropolous** [comment]
sorry about the hiccup @pospi ! I did become aware of the issue at mid-point in the tryorama work, and worked my way upstream to tryorama (coordinating with Jost) for a fix. The fix made it in subsequently, in the Agent branch that's since been merged to `sprout`. Will try to improve on my communication of something like that

**Comment by Connoropolous** [comment]
the solution is to merge `sprout` again into your branch, and to run `pnpm i` because this had to be fixed upstream in the tryorama dependency. As an aside, I am working through providing feedback to Jost on tryorama and in the meantime we are pointing at my temp fork of tryorama (@connoropolous/tryorama). As soon as the last fixes are in tryorama main, we can switch back to it

**Comment by Connoropolous** [comment]
I've just run the merge of updated sprout into that branch. So just pull and `pnpm i` then

**Comment by pospi** [comment]
Have done so, but still not getting any output (just a lot of verbose output from Holochain internals).

**Comment by Connoropolous** [comment]
@pospi can you make sure that the branch is compiling, and have this in a place where I can test this on the branch myself as well. We are into territory now where this is an unknown issue to me. As general info, the binary being executed by tryorama is now the `hc sandbox` execution  context for holochain, instead of the `holochain` binary, but I don't see why that should have made the difference.

**Comment by Connoropolous** [comment]
wow this got really weird lol.  https://github.com/holochain/tryorama/issues/128

Anyways, I've dug my way to the bottom of it I hope. It still needs fixes, but there's an ability to get at those logs at least for now. 

The solution is to set 
`TRYORAMA_LOG_LEVEL=debug` for the time being. I am capturing both necessary upstream improvements needed as well as in-repo improvements
