### ISSUE TITLE
Implement ability to augment built-in action types via Specification module

### ISSUE THREAD

**Issue by pospi** [holo-rea/holo-rea#38]
- [ ] define action record types in Specification module, keyed by action ID as a user-supplied string
- [ ] upgrade all record types which reference the `action` builtins directly to reference a combination of these, and records from an associated Specification zome. For now we can presume that only 1 Specification DNA can be connected to any consuming zome.

**Comment by fosterlynn** [comment]
I don't agree with this as a work item.  I basically think that we need to support the hard-coded actions, and any new ones should be added through VF, there is not really a place for user-definition here.  If we decide otherwise as a group, then I suspect it will be a very low priority; and will also need to have another layer of hard-coded action types, since there needs to be something defined here to enable communication between apps.

**Comment by pospi** [comment]
sweet, makes things quite a bit easier then
