### ISSUE TITLE
Building with yarn inside vagrant for windows gives an error

### ISSUE THREAD

**Issue by TheLaughableCoder** [holo-rea/holo-rea#71]
```
**error** An unexpected error occurred: "EPROTO: protocol error, symlink '../example/holorea-graphql-explorer' -> '/vagrant/holo-rea/node_modules/holorea-graphql-explorer'".
info If you think this is a bug, please open a bug report with the information provided in "/vagrant/holo-rea/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
I get this error. I've searched the interweb to find this error https://github.com/yarnpkg/yarn/issues/4908

Suggest an alternative to yarn for windows.

**Comment by pospi** [comment]
Checked it out- it looks like this is an issue with folder sharing between Virtualbox & Windows. Because you have cloned the repo into `/vagrant`, Yarn cannot correctly wire up modules- the filesystem can't deal with symlinks.

If the repository is cloned into a different folder that isn't shared with the host OS, `yarn` should work fine.
